name: PyGAD PyTest / Python 3.12

on:
  push:
    branches:
      - github-actions
      # - master

jobs:
  job_id_1:
    runs-on: ubuntu-latest
    name: PyTest Workflow Job

    steps:
      - name: Checkout Pre-Built Action
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0-beta.2' 

      - name: Build PyGAD from the Repository
        run: |
          # python3 -m pip install --upgrade build
          pip3 install setuptools==58.2.0
          pip3 install build
          python3.12 -m build --sdist --wheel
          # python3 -m build

      - name: Install PyGAD after Building the .whl File
        run: |
          find ./dist/*.whl | xargs python3.12 -m pip install

      - name: Install PyTest
        run: pip install pytest

      - name: Run the Tests by Calling PyTest
        run: |
          pytest
